# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

name: 'm-dnf no-mercy'
# Setup
title:            '던파 모바일 노머시 길드공지'
tagline:          '던파 모바일'
description:      '던파 모바일 노머시 '
url:              https://nenyounggam.github.io/
baseurl:          /

author:
  name:           'nenyounngam'
  url:            https://nenyounggam.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
